"""
Django settings for kursachback project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy
import django_heroku, dj_database_url
from urllib import parse
from decouple import config, UndefinedValueError

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9m@xz@mgou3zga))80h+uk2@p3eg-1gn$g0jui)-#o*o4uds3f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Honor the 'X-Forwarded-Proto' header for request.is_secure().
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
 
# Allow all host headers.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'db',
    'cart',
    'db.templatetags',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware'
]

ROOT_URLCONF = 'kursachback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates/account')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'kursachback.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
#DATABASE = {'default': dj_database_url.config() }
#DATABASES['default'] = dj_database_url.config()
#GDAL_LIBRARY_PATH = os.getenv('GDAL_LIBRARY_PATH')
#GEOS_LIBRARY_PATH = os.getenv('GEOS_LIBRARY_PATH')
#parse.uses_netloc.append('mysql')

#DATABASES = {'default': {}} 

DATABASES = {
        'default': {
           'NAME': 'heroku_a6fca33c3cc6106',
           'ENGINE': 'django.db.backends.mysql',
            'USER': 'bb04d450dd01d7',
            'PASSWORD': '1c53481c',
            'HOST': 'eu-cdbr-west-02.cleardb.net',
            'PORT': '3306',
       }
     }
#DATABASES = {'default': dj_database_url.config(default='mysql://bb04d450dd01d7:1c53481c@eu-cdbr-west-02.cleardb.net/heroku_a6fca33c3cc6106')}
#DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
#except UndefinedValueError:
#DATABASES = {'default': dj_database_url.config(default=os.environ["DATABASE_URL"])}
#DATABASES['default'].update(db_from_env)
#DATABASES['default']['ENGINE'] = 'django.db.backends.mysql'
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
ROOT_DIR = os.path.dirname(__file__)

django_heroku.settings(locals())
del DATABASES['default']['OPTIONS']['sslmode']
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/static/toursimage/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/toursimage/')

LOGIN_REDIRECT_URL = reverse_lazy('main')
LOGIN_URL = reverse_lazy('login')
LOGOUT_URL = reverse_lazy('logout')

CART_SESSION_ID = 'cart'
